# Generated by Django 5.1.3 on 2024-11-15 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_intro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
    ]
