# Generated by Django 5.1.3 on 2024-11-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_intro', '0002_remove_blogpost_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='email',
            new_name='user_email',
        ),
    ]
