# Generated by Django 5.1.3 on 2024-11-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_intro', '0004_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('students', models.ManyToManyField(to='db_intro.student')),
            ],
        ),
    ]
