# Generated by Django 5.1.3 on 2024-11-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_simpleorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simpleorder',
            name='product',
            field=models.CharField(choices=[('product1', 'Laptop'), ('product2', 'Smartphone'), ('product3', 'Headphones'), ('product4', 'Smartwatch'), ('product5', 'Tablet')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
