# Generated by Django 5.1.3 on 2024-11-19 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_simpleorder_order_date_simpleorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleorder',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
